### ISSUE TITLE
Have we been having problems?

### ISSUE THREAD

**Issue by coolaj86** [UtahJS/slack-coc#4]
Is this a reactive policy to some sort of concern or a proactive policy?

**Comment by maddie927** [comment]
Some of both. Something happens every few months, and people have expressed concern about not having _any_ sort of moderation process (including myself). But you can't hand the responsibility of moderating to a group of people without defining both what the rules are and what the responses should be.

**Comment by maddie927** [comment]
By "some of both" I mean that it is a reaction to specific problems, but that the CoC is for future problems.

**Comment by maddie927** [comment]
Closing unless there are further concerns
